### ISSUE TITLE
Issue with Implementation in GSA Server

### ISSUE THREAD

**Issue by ReconXMaverick** [ClaireWhere/gsabot#9]
In the welcome messages provided to new members and older chat messages the "roles" channel appears as "No Access". This is possibly due to two channels being named as "roles" (see below) and the cache find grabbing the older / other channel.

"No Access" Channel ID:
750424432736206969

"roles" Channel ID:
999895868671008939

Would it be possible to search for the channel in a specific category or maybe a config option for defining channel ID?

**Comment by ClaireWhere** [comment]
Fix already exists on dev branch (forgot to make issue on GitHub). Will be merging with main tomorrow.
